### ISSUE TITLE
adding HSV gradients does not work on stretch with python-pyqtgraph (0.10.0-1) 

### ISSUE THREAD

**Issue by jkotan** [syncope/lavue#1]
Hi,

When I try to run lavue (from master) on the stretch I get 

    jkotan@stretch-jk:~/sources/lavue$ bin/laVue 
    without hidra installed this does not make sense
    Traceback (most recent call last):
      File "bin/laVue", line 31, in <module>
	dialog = lavue.HidraLiveViewer()
      File "/home/jkotan/sources/lavue/lavue/hidraLiveViewer.py", line 132, in __init__
	self.imageW = imageWidget.ImageWidget(parent=self)
      File "/home/jkotan/sources/lavue/lavue/imageWidget.py", line 41, in __init__
	self.img_widget = imageDisplayWidget.ImageDisplayWidget(parent=self)
      File "/home/jkotan/sources/lavue/lavue/imageDisplayWidget.py", line 54, in __init__
	self.graditem = GI.GradientItem()
      File "/home/jkotan/sources/lavue/lavue/GradientItem.py", line 78, in __init__
	self.gradient = GradientEditorItem()
      File "/usr/lib/python2.7/dist-packages/pyqtgraph/graphicsItems/GradientEditorItem.py", line 448, in __init__
	self.removeTick(t)
      File "/usr/lib/python2.7/dist-packages/pyqtgraph/graphicsItems/GradientEditorItem.py", line 740, in removeTick
	self.updateGradient()
      File "/usr/lib/python2.7/dist-packages/pyqtgraph/graphicsItems/GradientEditorItem.py", line 524, in updateGradient
	self.gradient = self.getGradient()
      File "/usr/lib/python2.7/dist-packages/pyqtgraph/graphicsItems/GradientEditorItem.py", line 586, in getGradient
	stops.append((ticks[0][1], ticks[0][0].color))
    IndexError: list index out of range

It looks like adding HSV gradients fails.

Bests,
Jan

**Comment by jkotan** [comment]
I provide workaround, i.e. by commenting new HSV gradient in develop branch ( 7222a1648ac1523bdd442ba14654bfcc24c08118 )
